application: CloudAppDataStore
version: 1
runtime: python37
api_version: 1
threadsafe: true
handlers:
- url: /.*
  script: main.application
- url: /stylesheets
  static_dir: stylesheets  
  